create table roles(
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name text unique not null
 );
commit ;

create table users
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null,
    surname text not null,
    patronymic text not null,
    username text unique not null,
    email text,
    password text not null ,
    role_id int references roles(id) not null,
    is_deleted boolean default false,
    iin text
);
commit;

create table event
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null,
    start timestamp NOT NULL,
    "end" timestamp NOT NULL,
    completed boolean default false,
    description text,
    deleted boolean default false
);
commit;

create table file
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id int references event(id) not null,
    original_name text not null,
    fs_name text not null,
    extension text,
    path text not null,
    is_deleted boolean default false

);
commit;

create table category
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null
);
commit;



create table region
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null
);
commit;





create table source
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null
);
commit;



create table social_object
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text not null,
    latitude float,
    longitude float,
    start integer,
    "end" integer,
    category_type int references category(id) not null,
    source_type int references source(id) not null,
    region_type int references region(id) not null
);
commit;



create table menu_item
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    icon text not null,
    title text not null,
    path text,
    src text,
    parent_id int references menu_item(id)
);



create  table dictionary  (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data jsonb
);

